backend:
  name: git-gateway
  branch: main

local_backend: false

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "header"
    label: "Header Content"
    files:
      - name: "header-en"
        label: "Header (English)"
        file: "public/data/header-en.json"
        format: "json"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Subtitle", name: "subtitle", widget: "text" }
          - { label: "Small Text", name: "small", widget: "string" }
      - name: "header-he"
        label: "Header (Hebrew)"
        file: "public/data/header-he.json"
        format: "json"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Subtitle", name: "subtitle", widget: "text" }
          - { label: "Small Text", name: "small", widget: "string" }

  - name: "about"
    label: "About Content"
    files:
      - name: "about-en"
        label: "About (English)"
        file: "public/data/about-en.json"
        format: "json"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Content", name: "content", widget: "markdown" }
          - { label: "Button Text", name: "button", widget: "string" }
          - { label: "Bio", name: "bio", widget: "markdown", required: false }
      - name: "about-he"
        label: "About (Hebrew)"
        file: "public/data/about-he.json"
        format: "json"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Content", name: "content", widget: "markdown" }
          - { label: "Button Text", name: "button", widget: "string" }
          - { label: "Bio", name: "bio", widget: "markdown", required: false }

  - name: "gallery"
    label: "Gallery"
    file: "public/data/gallery.json"
    format: "json"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Category", name: "category", widget: "string" }
      - { label: "Images", name: "images", widget: "list", fields: [{ label: "Image", name: "url", widget: "image" }] }
      - { label: "Description", name: "description", widget: "text", required: false }
      - { label: "Date", name: "date", widget: "datetime" }
